apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: order-service
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: fabricio211/order-service
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: polardb-order
        chartPath: bitnami/postgresql
        remote: true
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_order
          image.tag: 13
  kubectl:
    manifests:
    - k8s/order.yml
    - k8s/service.yml
