spring:
  flyway:
    url: jdbc:postgresql://polardb-order-postgresql:5432/postgres
  r2dbc:
    url: r2dbc:postgresql://polardb-order-postgresql:5432/postgres
  active:
    profile: docker
  rabbitmq:
    host: polarmq-broker-rabbitmq

polar:
  catalog-service-url: http://catalog-service:9001/books/